return {
  { import = "plugins.tokyonight" },
  { import = "plugins.nvim-cmp" },
  { import = "plugins.smear-cursor" },
  { import = "plugins.neoscroll" },
  { import = "plugins.smoothcursor" },
  { import = "plugins.nvim-dap" },
  { import = "plugins.nvim-autopairs" },
  { import = "plugins.vim-visual-multi" },
  { import = "plugins.tiny-code-action" },
  { import = "plugins.neo-tree" },
  { import = "plugins.mason" },
  { import = "plugins.mason-lspconfig" },
  { import = "plugins.nvim-lspconfig" },
  { import = "plugins.telescope" },
  { import = "plugins.telescope-live-grep-args" },
  { import = "plugins.grug-far" },
  { import = "plugins.lualine" },
  { import = "plugins.alpha-nvim" },
  { import = "plugins.comment-nvim" },
  { import = "plugins.nvim-treesitter" },
}
